package vela.com.to;
// Generated 09/12/2013 05:29:11 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name="productos"
    ,catalog="db_sysalmacen"
)
public class Productos  implements java.io.Serializable {


     private Integer idpro;
     private int codigo;
     private String decripcion;
     private String cencos;
     private int cantidad;
     private double importe;

    public Productos() {
    }

    public Productos(int codigo, String decripcion, String cencos, int cantidad, double importe) {
       this.codigo = codigo;
       this.decripcion = decripcion;
       this.cencos = cencos;
       this.cantidad = cantidad;
       this.importe = importe;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpro", unique=true, nullable=false)
    public Integer getIdpro() {
        return this.idpro;
    }
    
    public void setIdpro(Integer idpro) {
        this.idpro = idpro;
    }

    
    @Column(name="codigo", nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="decripcion", nullable=false, length=40)
    public String getDecripcion() {
        return this.decripcion;
    }
    
    public void setDecripcion(String decripcion) {
        this.decripcion = decripcion;
    }

    
    @Column(name="cencos", nullable=false, length=10)
    public String getCencos() {
        return this.cencos;
    }
    
    public void setCencos(String cencos) {
        this.cencos = cencos;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="importe", nullable=false, precision=22, scale=0)
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }




}


